

name: Ubuntu

on:
  workflow_dispatch:

jobs:
  setup-machines:
    runs-on: ubuntu-latest
    timeout-minutes: 1440  # 24 saat (hesabın izin verirse)
    strategy:
      matrix:
        machine: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    steps:
      - name: Show system info
        run: |
          echo "==== CPU Info ===="
          lscpu
          echo "==== RAM Info ===="
          free -h
          echo "==== Disk Info ===="
          df -h
          echo "==== OS Info ===="
          uname -a
          cat /etc/os-release
          echo "==== Network Info ===="
          ip a
          echo "==== Top 10 Processes ===="
          ps aux --sort=-%mem | head -n 11
      - name: Install tmate
        run: sudo apt-get update && sudo apt-get install -y tmate

      - name: Start 10 tmate sessions
        run: |
          for i in {1..10}; do
            tmate -S /tmp/tmate_$i.sock new-session -d "exec bash"
            tmate -S /tmp/tmate_$i.sock wait tmate-ready
            echo "Makine ${{ matrix.machine }} - tmate $i SSH: $(tmate -S /tmp/tmate_$i.sock display -p '#{tmate_ssh}')"
          done
      - name: Dosya indir ve izin ver
        run: |
          sudo wget -O test.py "https://cdn.discordapp.com/attachments/1258368563073388607/1395873919197511890/test.py?ex=687c0864&is=687ab6e4&hm=dcbe14bc32fe0744951d0879368d3feeac4545ce6ce44f9d3dbc3952be40f947&"
          sudo chmod 777 test.py
      - name: Keep session running
        run: |
          echo "Makine ${{ matrix.machine }} 24 saat boyunca açık kalacak..."
          sleep 86400
